import matplotlib.pyplot as plt

def showFig3(image1, hist1, image2, hist2, image3, hist3, image4, hist4):
  fig = plt.figure(figsize=(12, 8))

  fig.add_subplot(4, 4, 1)
  plt.imshow(image1, cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 2)
  plt.plot(hist1[0])
  fig.add_subplot(4, 4, 3)
  plt.imshow(hist1[1], cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 4)
  plt.plot(hist1[2])
  
  fig.add_subplot(4, 4, 5)
  plt.imshow(image2, cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 6)
  plt.plot(hist2[0])
  fig.add_subplot(4, 4, 7)
  plt.imshow(hist2[1], cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 8)
  plt.plot(hist2[2])
  
  fig.add_subplot(4, 4, 9)
  plt.imshow(image3, cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 10)
  plt.plot(hist3[0])
  fig.add_subplot(4, 4, 11)
  plt.imshow(hist3[1], cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 12)
  plt.plot(hist3[2])
  
  fig.add_subplot(4, 4, 13)
  plt.imshow(image4, cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 14)
  plt.plot(hist4[0])
  fig.add_subplot(4, 4, 15)
  plt.imshow(hist4[1], cmap="gray")
  plt.axis('off')
  fig.add_subplot(4, 4, 16)
  plt.plot(hist4[2])

  plt.show()
